USE peopleblue;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  rol ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER',
  activo TINYINT NOT NULL DEFAULT 1,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS empleados (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dni CHAR(13) UNIQUE NOT NULL,
  nombres VARCHAR(80) NOT NULL,
  apellidos VARCHAR(80) NOT NULL,
  fecha_nacimiento DATE NULL,
  etnia VARCHAR(40) NULL,
  tipo_sangre VARCHAR(5) NULL,
  telefono VARCHAR(20) NULL,
  no_personal VARCHAR(30) NULL,
  domicilio VARCHAR(180) NULL,
  foto_path VARCHAR(255) NULL,
  observaciones TEXT NULL,
  activo TINYINT NOT NULL DEFAULT 1,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bitacora_impresion (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  dni CHAR(13) NOT NULL,
  tipo ENUM('CARNET','FICHA') NOT NULL,
  fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ip VARCHAR(45) NULL,
  resultado ENUM('OK','ERROR') NOT NULL DEFAULT 'OK'
);
